name: Deployment

on:
  push:
    branches:
      - main

env:
  WORKDIR: ${{ secrets.WORKDIR }}

jobs:
  deploy:
    name: Deployment on production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files.
        uses: actions/checkout@v3

      - name: Deploy files.
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          ARGS: "-rlgoDzvc -i --delete"
          TARGET: ${{ env.WORKDIR }}
          EXCLUDE: "/vendor, /.env"

      - name: Execute post-deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.WORKDIR }}
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan optimize:clear
            php artisan optimize
            php artisan l5-swagger:generate